/* Unified Loader – Excel-driven (Topic = condition; A1 sites) */
let REFERRALS=null, CURRENT_SPECIALTY=null, CURRENT_CONDITION=null;
async function loadReferralData(){ if(REFERRALS) return REFERRALS; const res=await fetch('master_normalised.json'); REFERRALS=await res.json(); return REFERRALS; }
window.addEventListener('DOMContentLoaded', async ()=>{ await renderSpecialties(); });
async function renderSpecialties(){ const data=await loadReferralData(); const c=document.getElementById('specialty-grid'); c.innerHTML=''; Object.keys(data).sort().forEach(spec=>{ const d=document.createElement('div'); d.className='specialty-tile'; d.textContent=spec; d.onclick=()=>renderConditions(spec); c.appendChild(d); }); }
async function renderConditions(spec){ CURRENT_SPECIALTY=spec; const data=await loadReferralData(); const list=document.getElementById('condition-list'); list.style.display='block'; document.getElementById('service-panel').style.display='none'; list.innerHTML=''; Object.keys(data[spec]).sort().forEach(cond=>{ const b=document.createElement('button'); b.className='condition-button'; b.textContent=cond; b.onclick=()=>renderServices(spec,cond); list.appendChild(b); }); }
async function renderServices(spec,cond){ CURRENT_CONDITION=cond; const data=await loadReferralData(); const services=data[spec][cond]||[]; drawServices(services); }
function drawServices(services){ const panel=document.getElementById('service-panel'); panel.style.display='block'; panel.innerHTML=''; const grouped={}; for(const s of services){ const p=s.provider||'Unknown'; (grouped[p]=grouped[p]||[]).push(s); } Object.keys(grouped).sort().forEach(provider=>{ const wrap=document.createElement('div'); wrap.className='provider-block'; const h=document.createElement('h3'); h.className='provider-title'; h.textContent=provider; wrap.appendChild(h); grouped[provider].forEach(svc=>wrap.appendChild(buildServiceCard(svc))); panel.appendChild(wrap); }); }
function buildServiceCard(svc){ const card=document.createElement('div'); card.className='service-card'; const h4=document.createElement('h4'); h4.textContent=svc.serviceName; card.appendChild(h4); const br=document.createElement('div'); if(svc.rasType) addBadge(br, svc.rasType); if(svc.method && svc.method.toLowerCase().includes('email')) addBadge(br,'Email'); if(svc.usc) addBadge(br,'USC/2WW','usc'); card.appendChild(br); if(svc.sites && svc.sites.length){ const d=document.createElement('div'); d.className='sites'; d.innerHTML='<strong>Sites:</strong> '+svc.sites.join(', '); card.appendChild(d); }
  const crit=document.createElement('div'); const parts=[]; if(svc.ageMin!=null) parts.push('≥'+svc.ageMin); if(svc.ageMax!=null) parts.push('≤'+svc.ageMax); const sex=svc.sex||'any'; crit.innerHTML='<strong>Age/Sex:</strong> '+(parts.join(' and ')||'All ages')+' • '+sex; card.appendChild(crit);
  if(svc.region){ const r=document.createElement('div'); r.className='region'; r.innerHTML='<strong>Region:</strong> '+svc.region; card.appendChild(r); }
  const contact=document.createElement('div'); contact.className='contact'; contact.innerHTML='<strong>Email:</strong> '+(svc.email||'—')+'<br><strong>Phone:</strong> '+(svc.phone||'—'); card.appendChild(contact);
  if(svc.notes){ const n=document.createElement('div'); n.className='notes'; n.innerHTML='<strong>Notes:</strong> '+svc.notes; card.appendChild(n); }
  return card; }
function addBadge(row,text,cls){ const b=document.createElement('span'); b.className='badge '+(cls||text); b.textContent=text; row.appendChild(b); }
// Filters
async function applyRegionFilter(region){ if(!CURRENT_SPECIALTY||!CURRENT_CONDITION) return; const data=await loadReferralData(); const all=data[CURRENT_SPECIALTY][CURRENT_CONDITION]||[]; const filtered=region==='All'?all:all.filter(s=>s.region===region); drawServices(filtered); }
async function applyAgeFilter(mode){ if(!CURRENT_SPECIALTY||!CURRENT_CONDITION) return; const data=await loadReferralData(); let list=data[CURRENT_SPECIALTY][CURRENT_CONDITION]||[]; if(mode==='adult') list=list.filter(s=>(s.ageMin??0)>=16); if(mode==='paeds') list=list.filter(s=>(s.ageMax??999)<18); drawServices(list); }
async function applyAgeSlider(value){ if(!CURRENT_SPECIALTY||!CURRENT_CONDITION) return; const data=await loadReferralData(); const list=(data[CURRENT_SPECIALTY][CURRENT_CONDITION]||[]).filter(s=>{ if(s.ageMin!=null && s.ageMin>value) return false; if(s.ageMax!=null && value>s.ageMax) return false; return true; }); drawServices(list); }
